### ISSUE TITLE
无法正常使用EncodeToNewMemoryStream(ReadOnlySpan<byte> data)方法

### ISSUE THREAD

**Issue by execute233** [lc6464/LC6464.Base16384#2]
报错如下：
![ZD$%4YO`}F3J D(8)3WQOP6](https://github.com/lc6464/LC6464.Base16384/assets/69996209/4bca6816-1837-4f76-9d78-40751e654bbb)

测试代码：
![Z`RXJE50W~(Z9ANO8{B9SYK](https://github.com/lc6464/LC6464.Base16384/assets/69996209/db74f40a-8739-4483-ae39-79eb83499c7b)

**Comment by lc6464** [comment]
@execute233 你排查一下是啥问题。

**Comment by lc6464** [comment]
我在 25G 二等座上挤着呢。

**Comment by execute233** [comment]
排查不了了，教育局发通知了延迟开学还叫我回去，垃圾学校，毁我青春。

**Comment by execute233** [comment]
哎嘿~
