### ISSUE TITLE
增加对不支持seeking的流的支持

### ISSUE THREAD

**Issue by execute233** [lc6464/LC6464.Base16384#6]
对于Console.OpenStandardInput()返回的流，它是不支持seeking，而您的EncodeToStream(Stream, stream)/DecodeToStream(Stream, stream)对流的长度进行了判断，传入这种类型的流时，将会发生异常：System.NotSupportedException: Stream does not support seeking.
虽然使用buffer[]能够解决这个问题，但是这将增加使用该方法的项目的代码量，望您能在将来发布的新版本中增加不支持seeking的流的支持。

**Comment by lc6464** [comment]
Please test all `XxcodeFromLongStreamToXxx` and all `XxcodeToXxx(Stream, ...)` with seekable `Stream` and unseekable `Stream` in version [2.1.0-Preview.1](https://www.nuget.org/packages/LC6464.Base16384/2.1.0-Preview.1), thank you.

**Comment by execute233** [comment]
six.

**Comment by lc6464** [comment]
Basically, do not six.

**Comment by execute233** [comment]
thank you,
